In [31]:
import pandas as pd 
import numpy as np

# Data Preparation

In [32]:
# To Load the data. 
df = pd.read_csv("train.csv")

# The shape of the dataset.
print(f"Loaded datat contains {df.shape[0]} rows and {df.shape[1]} columns.")

# The First Three rows of the dataset 
print(f" the first three rows: {df.head(3).to_string()}")

Loaded datat contains 891 rows and 12 columns.
 the first three rows:    PassengerId  Survived  Pclass                                                 Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0            1         0       3                              Braund, Mr. Owen Harris    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1      0          PC 17599  71.2833   C85        C
2            3         1       3                               Heikkinen, Miss. Laina  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S

In [33]:
# Explore the Data. 
print(f"The Datatypes:{df.dtypes}")

print(f"\n Statistical Summary")
print(df.describe().round(1))

miss_count = df.isnull().sum()
miss_per = (df.isnull().sum() / len(df) * 100).round(2)
table = pd.DataFrame({
    "Missing Count":miss_count, 
    "Missing Percentage": miss_per
})
print("\nMissing Values")
print(table[table["Missing Count"] >= 1])

The Datatypes:PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

 Statistical Summary
       PassengerId  Survived  Pclass    Age  SibSp  Parch   Fare
count        891.0     891.0   891.0  714.0  891.0  891.0  891.0
mean         446.0       0.4     2.3   29.7    0.5    0.4   32.2
std          257.4       0.5     0.8   14.5    1.1    0.8   49.7
min            1.0       0.0     1.0    0.4    0.0    0.0    0.0
25%          223.5       0.0     2.0   20.1    0.0    0.0    7.9
50%          446.0       0.0     3.0   28.0    0.0    0.0   14.5
75%          668.5       1.0     3.0   38.0    1.0    0.0   31.0
max          891.0       1.0     3.0   80.0    8.0    6.0  512.3

Missing Values
          Missing Count  Missing Percentage
Age                 177               19.87
Cabin               687               77.10
Embarked              2                0.22

In [34]:
# Clean the dataset
# First I have drop Nosie. 
df.drop(columns = ["PassengerId", "Name", "Ticket", "Cabin"], inplace = True)
print(f"The columns after cleaning:{list(df.columns)}")

# To handle numerical values 
Median_age = df['Age'].median() 
df['Age'].fillna(Median_age, inplace = True)
print(f"The Median value{Median_age}")


# To handle Categorical Values 
Mode_value = df['Embarked'].mode()[0]
df['Embarked'].fillna(Mode_value, inplace = True)
print(f"The Mode value: {Mode_value}")

# To handle datatypes
df['Pclass'] = df['Pclass'].astype("category")
print(f"The Pclass column has been changed to {df["Pclass"].dtypes}")

print(f"\nMissing Status:{df.isnull().sum()}")

The columns after cleaning:['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
The Median value28.0
The Mode value: S
The Pclass column has been changed to category

Missing Status:Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [35]:
# To Categorize Numerical Values in Python.
df['AgeGroup'] = pd.cut(
    x = df['Age'],
    bins = [0, 12, 19, 35, 69, 100],
    labels = ["Childern", "Teens", "Young adult", "Adult", "Seniors"]
)
df.head()

   Survived Pclass     Sex   Age  SibSp  Parch     Fare Embarked     AgeGroup
0         0      3    male  22.0      1      0   7.2500        S  Young adult
1         1      1  female  38.0      1      0  71.2833        C        Adult
2         1      3  female  26.0      0      0   7.9250        S  Young adult
3         1      1  female  35.0      1      0  53.1000        S  Young adult
4         0      3    male  35.0      0      0   8.0500        S  Young adult

In [ ]:
import matplotlib.pyplot as plt 
import seaborn as sns 

plt.figure(figsize = (10, 5))
plt.style.use("ggplot")
sns.countplot(x = df['AgeGroup'])
plt.xlabel("Age Groups")
plt.ylabel("Count Observations")
plt.show()

In [ ]:
plt.figure(figsize = (10, 5))
plt.style.use("ggplot")
sns.barplot(x = df['AgeGroup'], y = df['Survived'])
plt.show()

In [53]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,AgeGroup
0,0,3,male,22.0,1,0,7.2500,S,Young adult
1,1,1,female,38.0,1,0,71.2833,C,Adult
2,1,3,female,26.0,0,0,7.9250,S,Young adult
3,1,1,female,35.0,1,0,53.1000,S,Young adult
4,0,3,male,35.0,0,0,8.0500,S,Young adult
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Young adult
887,1,1,female,19.0,0,0,30.0000,S,Teens
888,0,3,female,28.0,1,2,23.4500,S,Young adult
889,1,1,male,26.0,0,0,30.0000,C,Young adult
890,0,3,male,32.0,0,0,7.7500,Q,Young adult

In [55]:
df.dtypes

Survived          int64
Pclass         category
Sex              object
Age             float64
SibSp             int64
Parch             int64
Fare            float64
Embarked         object
AgeGroup       category
Family_size       int64
dtype: object

In [54]:
# Feature creation 
df['Family_size'] = df['SibSp'] + df['Parch'] + 1
df['Isalone'] = (df[df['Family_size']== 1]).astype(int)
df['FarePerPerson'] = df['Fare'] /df['Family_size'].round(2)

ValueError: invalid literal for int() with base 10: 'female'